*2025 Spring DSAA 2011 Maching Learning*
## Lab Note 03
*Zixin Zhong, Hong Kong University of Science and Technology (Guangzhou)*


**Question 1.** Show that if $f:\mathbb{R}^d\to\mathbb{R}$ is a linear function, then $f$ must pass through the origin, i.e., $f(\mathbf{0})=0$ where $\mathbf{0}\in\mathbb{R}^d$ is the zero vector with $d$ dimensions.

**Question 2.** Show that if we have $n$ vectors $\mathbf{x}_i  \in\mathbb{R}^d, i = 1,\ldots, n$ and $n$ scalars $a_i\in \mathbb{R}, i = 1,\ldots, n$, a linear function satisfies
$$
f\bigg(\sum_{i=1}^n a_i\  \mathbf{x}_i\bigg) =  \sum_{i=1}^n a_i\ f(\mathbf{x}_i) .
$$
Hint: begin with the case of $n=2$.

**Question 3.** Let $f: \mathbb{R}\to\mathbb{R}$ be the absolute value function 
$$f(x) =|x|.$$
Is $f$ linear?

**Question 4.** Is a linear function affine? Is an affine function linear?

**Question 5.** Consider *Examples 1 and 2* of linear regression introduced during the lecture. Do the following for each example:
1. Show the linear system does not have a solution **by hand**.
1. Calculate the least squares solution using **only numpy**. Print the vector $\bar{\mathbf{w}}$.
2. Generate $10$ random new training samples $x_{\text{new}}$ and predict the corresponding value $\hat{y}_{\text{new}}$ for each $x_{\text{new}}$.

In [2]:
import numpy as np

x1 = np.array([[1, -7], [1, -5], [1, 1], [1, 5]])
y1 = np.array([-1, -1, 1, 1])

w1 = np.linalg.inv(x1.T @ x1) @ x1.T @ y1

print(w1)

# Example 2 data
X2 = np.array([[1, 1, 1],
               [1, -1, 1],
               [1, 1, 3],
               [1, 1, 0]])
y2 = np.array([1, 0, 2, -1])

w2 = np.linalg.inv(X2.T @ X2) @ X2.T @ y2

print(w2)

[0.2967033 0.1978022]
[-0.75        0.17857143  0.92857143]


In [8]:
x1_new = np.random.uniform(-5, 5, (10)).T
x1_new = np.vstack([np.ones(10), x1_new]).T

y1_new = x1_new @ w1
print(x1_new, y1_new)

x2_new = np.random.uniform(-5, 5, (10, 2)).T
x2_new = np.vstack([np.ones(10), x2_new]).T

y2_new = x2_new @ w2
print(x2_new, y2_new)

[[ 1.         -1.10197511]
 [ 1.          0.88504459]
 [ 1.         -4.99909751]
 [ 1.          1.31310752]
 [ 1.          3.10497878]
 [ 1.          3.09090207]
 [ 1.          4.49722205]
 [ 1.         -2.15741009]
 [ 1.          2.4876757 ]
 [ 1.          1.85838331]] [ 0.0787302   0.47176706 -0.69212918  0.55643885  0.91087492  0.90809052
  1.1862637  -0.13003716  0.78877102  0.6642956 ]
[[ 1.          3.62883853  0.96682053]
 [ 1.          3.95664257 -4.76433078]
 [ 1.         -2.40454251 -3.75510532]
 [ 1.          1.32281708 -4.80493011]
 [ 1.          0.92047612  2.52813557]
 [ 1.          0.61812244  2.48034527]
 [ 1.          3.19194909 -1.00225288]
 [ 1.          3.42793639  1.52689732]
 [ 1.          1.73025185 -4.3373991 ]
 [ 1.         -0.88172291 -1.51093623]] [ 0.7957688  -4.46747812 -4.6662661  -4.97550348  1.7619252   1.66355676
 -1.11067248  1.27996472 -4.46861133 -2.31046273]
